# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c2aaa548376a1dc7dc03e341e0925e67a5d569fdcdfa32b5ec3a4b43db43f028750c15342eb51ce630c2b57aace1cdef44761044796b04cda80207771219d9c

test:
  secret_key_base: 991dfafa090523d825ad336057b77debf3b534abfab35fa26f7e7772717869b01c3c434053b7d905d47bd298ca9c17f28ee2d8deec62308bc53c9c89e05edc11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
